### ISSUE TITLE
Error related to JSON

### ISSUE THREAD

**Issue by Cobralilie** [althonos/InstaLooter#160] opened 2018-04-13 10:01 UTC
## Library version

```
instalooter v1.0.0
```

## Environment

Linux Mint 18.2 Cinnamon

## Error description - runtime

I'm getting a error related to JSON, which differs on the Python version used

### Reproducible test case

```
instalooter post https://www.instagram.com/p/BYZJpXLBQMv/?taken-by=themightyi [<directory>] --traceback
```

### Expected behaviour

Downloading one picture

### Actual behaviour

For Python 2.7.12:

```
2018-04-13 10:56:09 grafzahl-UX490UA instalooter.cli[16402] NOTICE Starting download of `https://www.instagram.com/p/BYZJpXLBQMv/?taken-by=themightyi`
2018-04-13 10:56:09 grafzahl-UX490UA instalooter.cli[16402] CRITICAL No JSON object could be decoded
Traceback (most recent call last):
  File "/home/grafzahl/.local/lib/python2.7/site-packages/instalooter/cli/__init__.py", line 170, in main
    dlpbar_cls=None if args['--quiet'] else TqdmProgressBar)
  File "/home/grafzahl/.local/lib/python2.7/site-packages/instalooter/looters.py", line 811, in download
    new_only, condition)
  File "/home/grafzahl/.local/lib/python2.7/site-packages/instalooter/looters.py", line 583, in _fill_media_queue
    for media in six.moves.filter(_condition, medias_iter):
  File "/home/grafzahl/.local/lib/python2.7/site-packages/instalooter/looters.py", line 775, in medias
    info = self.info
  File "/home/grafzahl/.local/lib/python2.7/site-packages/instalooter/looters.py", line 743, in info
    self._info = self.get_post_info(self.code)
  File "/home/grafzahl/.local/lib/python2.7/site-packages/instalooter/looters.py", line 320, in get_post_info
    return res.json()['graphql']['shortcode_media']
  File "/home/grafzahl/.local/lib/python2.7/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
```

For Python 3.5.2 in a virtual environment:

```
2018-04-13 11:16:23 grafzahl-UX490UA instalooter.cli[17115] NOTICE Starting download of `https://www.instagram.com/p/BYZJpXLBQMv/?taken-by=themightyi`
2018-04-13 11:16:23 grafzahl-UX490UA instalooter.cli[17115] CRITICAL Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/grafzahl/tutorial_env/lib/python3.5/site-packages/instalooter/cli/__init__.py", line 170, in main
    dlpbar_cls=None if args['--quiet'] else TqdmProgressBar)
  File "/home/grafzahl/tutorial_env/lib/python3.5/site-packages/instalooter/looters.py", line 811, in download
    new_only, condition)
  File "/home/grafzahl/tutorial_env/lib/python3.5/site-packages/instalooter/looters.py", line 583, in _fill_media_queue
    for media in six.moves.filter(_condition, medias_iter):
  File "/home/grafzahl/tutorial_env/lib/python3.5/site-packages/instalooter/looters.py", line 775, in medias
    info = self.info
  File "/home/grafzahl/tutorial_env/lib/python3.5/site-packages/instalooter/looters.py", line 743, in info
    self._info = self.get_post_info(self.code)
  File "/home/grafzahl/tutorial_env/lib/python3.5/site-packages/instalooter/looters.py", line 320, in get_post_info
    return res.json()['graphql']['shortcode_media']
  File "/home/grafzahl/tutorial_env/lib/python3.5/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.5/json/__init__.py", line 319, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.5/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.5/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by GabMar** [comment] 2018-04-13 12:02
The public endpoint https://www.instagram.com/{username}/?__a=1 (and all the others public endpoints) respond with a 403 (Access Denied), so the script can't process any response JSON

**Comment by althonos** [comment] 2018-04-13 15:45
Duplicate of #159 . @GabMar, thanks for looking into this, I'll revert back to the previous method I was using (which is, extract that information from the whole HTML using a regex instead of relying on that API).

**Closed by althonos** 2018-04-13 15:45 UTC
