### ISSUE TITLE
[feature request] using a wish-list file with desired @users to make downloads easier?

### ISSUE THREAD

**Issue by grissom02** [althonos/InstaLooter#93] opened 2017-09-09 17:22 UTC
Hello!
My idea is to create a whish-list file with all the instagram users we want to rip, and make InstaLooter to use it to download all of them automatically with a -wishlist argument, like: [$ python -m instaLooter wishlist.txt -v -u [userlogin] -p [userpassword] -N ] ; downloading the @username to ./username folder as well.  
Is this possible?

**Comment by polyzen** [comment] 2017-09-09 20:42
Duplicate of #17

**Comment by grissom02** [comment] 2017-09-09 22:31
ok, I'm sorry. I'm no coding at all, and I did not understand how to use it from #17. Can someone please explain how to use that feature, please?

**Comment by althonos** [comment] 2017-09-10 18:28
This is not implemented yet, but I'm currently working on it. Please follow the #17 thread, I'll develop the usage there.

**Closed by althonos** 2017-09-10 18:28 UTC

**Comment by althonos** [comment] 2017-09-11 10:18
@grissom02 : make sure you are using version `v0.12.0` at least, and check http://instalooter.readthedocs.io/en/latest/batch.html.

**Comment by grissom02** [comment] 2017-09-14 09:58
@althonos thank you! I'll take a look into it.
