### ISSUE TITLE
ImportError: No module named instalooter.cli

### ISSUE THREAD

**Issue by intergleam** [althonos/InstaLooter#168] opened 2018-04-20 20:09 UTC
Followed the instruction and got error

```
osboxes@osboxes:~/_pr/videodl$ instalooter post BamZ78YDQ44 ss
Traceback (most recent call last):
  File "/home/osboxes/.local/bin/instalooter", line 7, in <module>
    from instalooter.cli import main
ImportError: No module named instalooter.cli
```

**Comment by distantstar** [comment] 2018-04-29 13:33
This issue is fixed with the recent commit, I think. I can't reproduce it anymore.

**Closed** 2018-07-31 15:39 UTC
Labels: bug
