### ISSUE TITLE
Instagram changed its inner data structure

### ISSUE THREAD

**Issue by lynxrv21** [althonos/InstaLooter#145] opened 2018-03-13 22:48 UTC
Getting the same error for any username I try.
```
instaLooter instagram
00:41:53 - WARNING - Could not find page of user: instagram
00:41:53 - WARNING - No medias found.
```

**Comment by bilyboy785** [comment] 2018-03-14 07:28
+1

**Comment by bilyboy785** [comment] 2018-03-14 09:08
Do you think fix this or it is normal ?

**Comment by jnskw** [comment] 2018-03-14 09:12
Instagram might have changed the structure of its data.

I think Instagram-Scraper had a similar Problem: 
https://github.com/rarcega/instagram-scraper/commit/3840aab1386f5923aa34827b688d67944a8a4ae2

**Comment by lynxrv21** [comment] 2018-03-14 09:36
So, is anyone going to fix it here, or I have to do it by myself?

**Comment by bilyboy785** [comment] 2018-03-14 13:16
if you fix it, can you share it ? :)

**Comment by lynxrv21** [comment] 2018-03-14 22:51
No luck with this yet.
Looks like we need @althonos to help us.

**Comment by bilyboy785** [comment] 2018-03-15 14:27
Only he does not look active anymore.

**Comment by althonos** [comment] 2018-03-15 16:51
My studies are calling, so I don't have much time to invest in this.
The main issue is that IG changed not only its internal data representation, but also the method used to query those data. This is what makes fixing a pain. I'll try to see what I can do.

**Comment by AbysmalBiscuit** [comment] 2018-03-15 17:48
Hey,

I've had a look at the new json structure, and as @althonos says it's different from what instaLooter expects to find, hence why there is an internal KeyError when the response data gets processed for the firt time in `core.py` by:
` media_info = data['entry_data'][self._page_name][0][self._section_name]['media']`

From analyzing the json reponse, all the information that may be wanted is in there: image src url, metadata etc...

This is type of code that's needed to get what I think should be all the media info that instaLooter expects ( this will just print the response contents of all posts loaded in the first response):
https://gist.github.com/AbysmalBiscuit/0799d5ed77e9ec6415836d8c8da9fd2d

**Comment by althonos** [comment] 2018-03-15 17:53
I've got a working fix on the `dev` branch you can install with:
```
pip install --user --upgrade https://github.com/althonos/InstaLooter/archive/dev.zip
```

I still want to check the code in greater detail before pushing a release, but at least it downloads pics as intended for both users and hashtags.

**Comment by AbysmalBiscuit** [comment] 2018-03-15 17:58
@althonos Thanks for the quick fix!

**Comment by althonos** [comment] 2018-03-15 18:08
@AbysmalBiscuit : fixed, thanks.

**Comment by oferchen** [comment] 2018-03-17 17:25
another issue could be related,
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/dist-packages/instaLooter/worker.py", line 70, in run
    self._download_photo(media)
  File "/usr/local/lib/python2.7/dist-packages/instaLooter/worker.py", line 133, in _download_photo
    self._add_metadata(photo_name, media)
  File "/usr/local/lib/python2.7/dist-packages/instaLooter/worker.py", line 106, in _add_metadata
    self._get_caption(metadata).encode('utf-8'),
  File "/usr/local/lib/python2.7/dist-packages/instaLooter/worker.py", line 45, in _get_caption
    return metadata['edge_media_to_caption']['edges'][0]['node']['text']
IndexError: list index out of range

**Comment by JonasGrobe** [comment] 2018-03-18 20:51
Bug still occurs when using a timeframe.
It worked again when I changed line 416 in core.py from "for media in page[media]['edges']:" to "for media in page[medias]['edges']:"

**Comment by Bigben83** [comment] 2018-03-19 10:24
I pulled the dev branch and the could not find page of user  is still showing ?  should i be doing something else ?

**Comment by althonos** [comment] 2018-03-19 12:20
@Bigben83 : could you give me some parameters so that I can reproduce this ? It works just fine with a public user on my machine.

**Comment by Bigben83** [comment] 2018-03-19 20:06
@althonos this is what i have been using
` /usr/local/bin/instaLooter sawyerhartman /home/dev/public_html/instagram/sawyerhartman -T {username}.{datetime} -q --add-metadata -v -N -n 50`

**Comment by rajnishcseku** [comment] 2018-03-21 09:26
@althonos I am also having the same issue which @Bigben83 is having.

**Comment by althonos** [comment] 2018-03-21 13:54
@Bigben83 @rajnishcseku @JonasGrobe @oferchen @AbysmalBiscuit @jnskw @lynxrv21 @bilyboy785 : If you want to test the new version, you can pull from the `dev` branch. The codebase is brand new, but the CLI should be very familiar, and most problems should be fixed. **Note that I didn't test the *login* at all since I have no IG account and I don't know if the login procedure used before still works !**

I'll release once I've got the documentation updated and the API stabilised.

In the meantime:
```
pip install --user -U https://github.com/althonos/InstaLooter/archive/dev.zip
```

**Comment by lynxrv21** [comment] 2018-03-21 15:01
@rajnishcseku try to skip step 2

**Comment by djvanguard** [comment] 2018-03-21 15:33
I did similar to @rajnishcseku but I did skip step 2.  (So just uninstall, and then the install of the dev.zip)
It also says it installed UNKNOWN-0.0.0 and then doesn't seem to know what InstaLooter is when I try to run it.   Do I need to find and extract the dev.zip somewhere?

**Comment by JonasGrobe** [comment] 2018-03-21 15:42
@djvanguard pip install setuptools --upgrade, then try again

**Comment by rajnishcseku** [comment] 2018-03-21 19:54
@JonasGrobe I ran the command given by you also uninstalled the instaLooter (i.e. skipping step 2)

Now when I try to run command "instaLooter inspirational.theory" output comes:

_c:\>instaLooter inspirational.theory
'instaLooter' is not recognized as an internal or external command,
operable program or batch file._

Do I need to set some some kind of environment variable in my laptop or is there any other problem?

**Comment by althonos** [comment] 2018-03-21 20:00
@rajnishcseku: and on `python -m instalooter inspirational.theory` ?

**Comment by oferchen** [comment] 2018-03-21 23:06
@althonos
it took some effort I added some entries to init, 
try:
    from .cli import main
    from .core import InstaLooter
    from . import urlgen
except ImportError:
    pass

while getting a bit disappointing result,
invalid format for --time parameter: None
    (format is [D]:[D] where D is an ISO 8601 date)

I never user --time-parameter in original command line and also login doesn't work

**Comment by rajnishcseku** [comment] 2018-03-22 08:31
@althonos I ran the command `python -m instalooter inspirational.theory`

**Output:**

C:\Users\rajnish.rana>python -m instalooter inspirational.theory
C:\Users\rajnish.rana\AppData\Local\Programs\Python\Python36\python.exe: No module named instalooter

**Comment by oferchen** [comment] 2018-03-23 08:04
@rajnishcseku it looks like the module directory on windows is not instaLooter
but windows is not usually case sensitive so I'm not sure how python modules are
I would suggest to just rename the directory of the module from instalooter to instaLooter

**Comment by althonos** [comment] 2018-03-25 13:59
An alpha release of `v1.0.0` is out. I consider this issue closed, as the new structure is handled fine.

#150 was opened to fix the non-working login procedure.

**Closed by althonos** 2018-03-25 13:59 UTC
Labels: bug
