### ISSUE TITLE
Not detecting private accounts

### ISSUE THREAD

**Issue by raphaelbernardino** [althonos/InstaLooter#84] opened 2017-07-19 00:42 UTC
Output for private accounts is bugged. Or changed, i don't know.

#### Test for: raphaelbernardino
Real output:
`$ instaLooter raphaelbernardino`
`21:35:05 - WARNING - No medias found.`

Expected output:
`$instaLooter raphaelbernardino`
`21:35:05 - WARNING - Profile raphaelbernardino is private, and you are not following it.`
`21:35:05 - WARNING - No medias found.`

#### Version
`$instaLooter --version`
`instaLooter 0.10.2`

**Comment by althonos** [comment] 2017-07-19 09:31
Thanks for the detailed report !
This is actually caused by profiles like yours with only a few post, I'll get it fixed.

**Comment by althonos** [comment] 2017-07-19 10:15
Fixed in upcoming `v0.11.0` version (your IG profile is now the test case 😄).

**Closed by althonos** 2017-07-19 10:15 UTC
