### ISSUE TITLE
[Feature request] Instagram Stories support

### ISSUE THREAD

**Issue by Lambik** [althonos/InstaLooter#65] opened 2017-05-11 08:23 UTC
Hi,

Would this script work/be made to work with the relatively new concept of Stories?

Best regards!

**Comment by althonos** [comment] 2017-05-11 11:29
Duplicate of #36, where I said I had no idea how to do it yet (I don't have an Instagram account actually). But any help is welcome !

**Closed by althonos** 2017-05-11 11:29 UTC

**Comment by Lambik** [comment] 2017-05-11 12:29
Oh dang sorry, I thought I had read all the previous issues and must've overlooked it. Didn't mean to be annoying!
