### ISSUE TITLE
A few issues I came across while using InstaLooter

### ISSUE THREAD

**Issue by jeanmarctst** [althonos/InstaLooter#94] opened 2017-09-11 16:46 UTC
Tout d'abord j'aimerais te remercier althonos pour ce petit programme qui est vraiment très utile. Je me suis un peu amusé avec, en l'intégrant à quelques batchs pour simplicité d'utilisation, et de manière générale ça marche bien. Je continue en anglais pour que tout le monde comprenne.

I came across a few issues with the program:
- The {{height}} argument for the template seems to be bugged and crashes the command
- Metadata inclusion works well when fetching accounts, but is not included when fetching a single post.
- Metadata doesn't work on videos.
- You can't use parenthesis in the template in batch loops (not really dramatic but useful to know)

Maybe I'm doing something wrong myself, I'm no specialist, but that's what I found out after using instaLooter for a few days. Don't worry, it still does 99% of what I want so I'm very pleased :)

#JM

**Comment by althonos** [comment] 2017-09-12 18:14
Merci pour le retour, c'est toujours sympa de recevoir ce genre de messages ! :smile:

> The {{height}} argument for the template seems to be bugged and crashes the command
You should use `{height}`, not `{{height}}`, or else Python will escape the brackets !  The following command works as intended on my machine: 
```console
python -m instaLooter instagram /tmp -T \{id\}.\{height\} -v
```

> Metadata doesn't work on videos.
This is completely normal: there's not pure-python solution to edit metadata of a `mp4` file, so you can't write the metadata like you would with pictures using `piexif`. A fork started some time ago to use external programs, but I won't merge since I would like to maintain a pure-python alternative.

> Metadata inclusion works well when fetching accounts, but is not included when fetching a single post
Probably a piece of code I forgot to call somewhere, I'll check that and add tests.

> You can't use parenthesis in the template in batch loops (not really dramatic but useful to know)
Are you escaping the parenthesis (using `\` ?)

Thanks again for the feedback !

**Comment by jeanmarctst** [comment] 2017-09-15 20:33
Thank you for your enlightening answer :)

- OK about the {height} argument, I just didn't understand why {{width}} would work but not {{height}}.

- About the medatada on mp4 files, do you mean that a pure python solution to add metadata has not yet been coded? Or that it's simply impossible?

- Can't wait to know more about the problem with metadata on single post commands. Whether it's me or if it's something that could be fixed! Thanks in advance :)

- OK so that's me never having coded in python. I knew it would be some simple solution like that. My solution was, I simply replaced parenthesis with brackets.

**Comment by althonos** [comment] 2017-09-17 15:10
* `{{width}}` works ? Now that's strange ! It doesn't on my Linux, though, you end up with a file called `"1598220030100386985.908.{width}.jpg"` if your template is `\{id\}.\{height\}.\{\{width\}\}` (with escape characters).

* A pure python solution has yet to be coded indeed, or at least a proper wrapper, for an existing library. Current workaround is to use subprocesses to call system tools that can do that (such as ffmpeg I guess), so it's not great.

* So I checked and metadata is added to the images properly even in *post* mode, at least in the dev version (so soon to be released `v0.13.1`). Yet, the caption is not added, because IG changed the location of the caption on some pages, but in the end at least the **Image creator** tag and the **DateTimeOriginal** tag are added.

**Comment by althonos** [comment] 2017-09-17 16:15
Caption issue should be fixed in `v0.13.1`.

**Comment by jeanmarctst** [comment] 2017-09-18 20:18
Yep, {{width}} absolutely worked when I tried, but not {{height}}. That's why I thought it was pretty weird.

Yeah I should have told you that the "created by" info was still working. I'm really not a specialist of this stuff so it didn't even occur to me that it was also considered metadata. So yes, what's missing is the caption thing absolutely.
Sorry I should have been more specific.

**Comment by jeanmarctst** [comment] 2017-09-19 09:05
Hello again, I just tried fetching posts again after updating, and here it is, metadata works perfectly!

Thanks a lot Althonos :)

**Comment by althonos** [comment] 2017-09-19 14:44
Great ! No problem :)

**Closed by althonos** 2017-09-19 14:44 UTC
Labels: bug, question
