### ISSUE TITLE
not download pic completely

### ISSUE THREAD

**Issue by gnu-like** [althonos/InstaLooter#149] opened 2018-03-23 16:53 UTC
there is no error but download just 13 byte every photo so 13 byte mean nothing

**Comment by JonasGrobe** [comment] 2018-03-23 16:56
Open it with a text editor - does it say "Access denied"? 
I have exactly the same problem (#148 )

**Comment by kpuljek** [comment] 2018-03-23 21:14
Same here

**Comment by althonos** [comment] 2018-03-24 18:42
Closing as a duplicate of #148.

**Closed by althonos** 2018-03-24 18:42 UTC
