### ISSUE TITLE
Query Rate Exceeded

### ISSUE THREAD

**Issue by distantstar** [althonos/InstaLooter#172] opened 2018-04-29 13:36 UTC
## Library version

*What's the installed library version ? Check with `instalooter --version`*:

`
$ ~/.local/bin/instalooter --version
instalooter 2.0.1
`

## Environment

*Describe here your environment, including:*

* *OS*

`$ uname -a
Linux distantstah.com 4.4.33-gentoo #1 SMP Sun Nov 20 13:00:40 MST 2016 x86_64 Intel(R) Xeon(R) CPU E5620 @ 2.40GHz GenuineIntel GNU/Linux`
* *Python version*

`$ python --version
Python 3.4.5
`
* *`setuptools` version if reporting an issue with installation*

`$ qlist -Iv setuptools                                                                                          
dev-python/setuptools-36.7.2`
* *non-standard Python implementation if any*

`None`

## Error description - installation

*If you have an issue with installation, make sure you use a recent `setuptools` version
before filing a bug ! If the error is still there, describe the command you used to 
install, and make sure you reported your environment in details.*

`None`

## Error description - runtime

*If you have an issue at runtime, include the required information below:*

### Reproducible test case

*Are you using the CLI ? If so, include a command that can be used to re-raise the 
error, with actual arguments anybody can try:*

```
$ ~/.local/bin/instalooter user modeltraveling                                                                  
2018-04-29 06:09:24 distantstah.com instalooter.cli[19464] NOTICE Starting download of `modeltraveling`
2018-04-29 06:09:25 distantstah.com instalooter.cli[19464] CRITICAL Query rate exceeded (wait before next run)
```

*Are you using the API ? If so, include a small snippet that can be used to re-raise the
error:*

```python
from instalooter.looters import ...
```

### Expected behaviour

*What's supposed to happen ? That's were you can ask for a new feature as well*

```Download the files and videos without limit```

### Actual behaviour

*What's actually happening ? Leave empty if asking for a new feature*

```It's limiting how much we can download```

**Comment by althonos** [comment] 2018-04-29 14:07
Duplicate of #171 and #170.

**Closed by althonos** 2018-04-29 14:07 UTC
