### ISSUE TITLE
"account not found" for all accounts

### ISSUE THREAD

**Issue by mattshelton** [althonos/InstaLooter#159] opened 2018-04-13 01:11 UTC
## Library version

```
instalooter v1.0.0
```

## Environment

*Describe here your environment, including:*

* MacOS 10.13.4
* Python 3.6.5

## Error description - runtime

For every user account download attempted, the error "account not found" is raised, even for public accounts.

### Reproducible test case

```
> instalooter user justinbieber . -v -T "{username}.{datetime}.{id}" --traceback
2018-04-12 21:05:01 host.local instalooter.cli[22140] NOTICE Starting download of `justinbieber`
2018-04-12 21:05:02 host.local instalooter.cli[22140] CRITICAL account not found: justinbieber
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/instalooter/pages.py", line 152, in _user_data
    data = res.json()
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 892, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/instalooter/cli/__init__.py", line 170, in main
    dlpbar_cls=None if args['--quiet'] else TqdmProgressBar)
  File "/usr/local/lib/python3.6/site-packages/instalooter/looters.py", line 418, in download
    pages_iterator = self.pages()   # type: Iterable[Dict[Text, Any]]
  File "/usr/local/lib/python3.6/site-packages/instalooter/looters.py", line 691, in pages
    it = ProfileIterator.from_username(self._username, self.session)
  File "/usr/local/lib/python3.6/site-packages/instalooter/pages.py", line 160, in from_username
    data = cls._user_data(username, session)['graphql']['user']
  File "/usr/local/lib/python3.6/site-packages/instalooter/pages.py", line 154, in _user_data
    raise ValueError("account not found: {}".format(username))
ValueError: account not found: justinbieber
```

### Expected behaviour

All of Justin's pictures and videos download. (Picked an account I knew should exist...)

### Actual behaviour

None do.

**Comment by deepak728** [comment] 2018-04-13 11:46
I am facing the same issue.

**Comment by althonos** [comment] 2018-04-13 15:46
I'll try to look into this, looks like the API that allowed to get JSON directly from a public page is not available anymore. I'll have to resign to using a regex as I did before.

**Comment by Yazeedot** [comment] 2018-04-13 20:26
same issue 
win 7 
python 2.7

```
`C:\s>python -m instalooter user getmybook -n 20
2018-04-13 23:23:33 Lenovo-PC instalooter.cli[6544] NOTICE Starting download of
`getmybook`
2018-04-13 23:23:33 Lenovo-PC instalooter.cli[6544] CRITICAL account not found:
getmybook`
```

**Comment by 030jmk** [comment] 2018-04-14 13:48
The JSON data can still be found on the respective profile pages within the first script tag in the body.  Isolating the content of the script using BeautifulSoup or PyQuery and getting rid of the variable name and semicolon `[21:-1] ` results in valid JSON which has the information to the images.
After loading the JSON, the link to the image(s) can be found at `['entry_data']['ProfilePage'][0]['graphql']['user']['edge_owner_to_timeline_media']['edges'][i]['node']['display_url']` where `i in range(12)`

> from requests import get
>from pyquery import PyQuery as pq
> import json
> doc = pq(get(URL_TO_PROFILE).text)
> data = (doc('script')[2].text)[21:-1]
> for i in range(12):
>...  print(json.loads(data)['entry_data']['ProfilePage'][0]['graphql']['user']['edge_owner_to_timeline_media']['edges'][i]['node']['display_url'])

**Comment by althonos** [comment] 2018-04-14 13:51
Duplicate of #157 (caused by IG changing its API endpoints).

**Closed by althonos** 2018-04-14 13:51 UTC
Labels: bug
